### ISSUE TITLE
Quadratic objective not allowed via JuMP

### ISSUE THREAD

**Issue by mpf** [MPF-Optimization-Laboratory/ConicIP.jl#15]
```
using JuMP, ConicIP
m = Model(solver=ConicIPSolver())
@variable(m, x ≥ 0)
@objective(m, Min, x^2)
julia> solve(m)
ERROR: Solver does not support quadratic objectives
 in setquadobjterms!(::MathProgBase.SolverInterface.ConicToLPQPBridge, ::Array{Int32,1}, ::Array{Int32,1}, ::Array{Float64,1}) at /Users/mpf/.julia/v0.5/MathProgBase/src/SolverInterface/LinearQuadratic.jl:71
 in addQuadratics(::JuMP.Model) at /Users/mpf/.julia/v0.5/JuMP/src/solvers.jl:484
 in #build#114(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at /Users/mpf/.julia/v0.5/JuMP/src/solvers.jl:422
 in (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at ./<missing>:0
 in #solve#109(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at /Users/mpf/.julia/v0.5/JuMP/src/solvers.jl:166
 in solve(::JuMP.Model) at /Users/mpf/.julia/v0.5/JuMP/src/solvers.jl:148
```

**Comment by mlubin** [comment]
JuMP currently supports either [plain QP](http://mathprogbasejl.readthedocs.io/en/latest/lpqcqp.html) or [conic LPs](http://mathprogbasejl.readthedocs.io/en/latest/conic.html). There's been some discussion of allowing quadratic terms in the conic format. @blegat

**Comment by mpf** [comment]
Thanks for clarifying!

**Comment by blegat** [comment]
Yes this is definitely on my TODO list :)

**Comment by mpf** [comment]
In the meantime, is there a workaround that would still give ConicIP an opportunity to recast the quadratic objective term as an SOC constraint? I don't expect JuMP to do this, but only give ConicIP a chance to make the reformulation. (Presumably Convex.jl is doing this automatically.)

**Comment by mlubin** [comment]
You could implement the [LinearQuadratic](http://mathprogbasejl.readthedocs.io/en/latest/lpqcqp.html) interface and act like a QCQP solver. We have [some code](https://github.com/JuliaOpt/MathProgBase.jl/blob/31c6966ca22e0c90b9802335a6bbd31bebdc5e04/src/SolverInterface/conic_to_lpqp.jl) that turns a generic conic solver into a generic LinearQuadratic solver. You could use that as a starting point or add logic there to reformulate quadratic objectives.

**Comment by mlubin** [comment]
FYI the infrastructure is now in place to support modeling problems with quadratic objectives and conic constraints in JuMP. It should "just work" with JuMP `master` if ConicIP implements the corresponding functionality in [MathOptInterface](https://github.com/JuliaOpt/MathOptInterface.jl). It's not entirely documented, but it's ready for early testing.
