### ISSUE TITLE
MathProgBase tests

### ISSUE THREAD

**Issue by mlubin** [MPF-Optimization-Laboratory/ConicIP.jl#2]
After https://github.com/JuliaOpt/MathProgBase.jl/commit/132ffb4762528ac5a8481982244259fd25e1d460 I was able to get the following tests passing:

```
coniclineartest(ConicIPSolver(verbose = false), duals=true)
conicSOCtest(ConicIPSolver(verbose = false), duals=true)
conicSDPtest(ConicIPSolver(verbose = false, optTol = 1e-6))
```

You may want to run these with your unit tests (after the next tag of MPB)

**Comment by gabgoh** [comment]
Thanks for fixing this, I wanted to put that in there!

**Comment by gabgoh** [comment]
Oh wait - forgot about the tagging issue. I commented it out again. Will uncomment when the tag comes.
