### ISSUE TITLE
DualInfeasible status is invalid

### ISSUE THREAD

**Issue by mlubin** [MPF-Optimization-Laboratory/ConicIP.jl#8]
The `:DualInfeasible` status returned by ConicIP is not a [standard return status](http://mathprogbasejl.readthedocs.io/en/latest/solverinterface.html#status). The convention is for this to be `:Unbounded`, even though it's slightly misleading. There's definitely scope for clarifying duality failure states, but if the solver isn't doing any checking of whether dual infeasible means primal unbounded or primal infeasible, I think it's ok to go ahead and return `:Unbounded` through the MathProgBase interface. I can throw together a PR for this if you'd like.

**Comment by gabgoh** [comment]
i can take care of this, i'm deep in the code anyway

**Comment by gabgoh** [comment]
done
